/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLabelRouteImport } from './routes/private-label'
import { Route as OurBrandsRouteImport } from './routes/our-brands'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OurBrandsBrandSlugRouteImport } from './routes/our-brands.$brandSlug'
import { Route as InsightsArticleIdRouteImport } from './routes/insights/$articleId'

const PrivateLabelRoute = PrivateLabelRouteImport.update({
  id: '/private-label',
  path: '/private-label',
  getParentRoute: () => rootRouteImport,
} as any)
const OurBrandsRoute = OurBrandsRouteImport.update({
  id: '/our-brands',
  path: '/our-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurBrandsBrandSlugRoute = OurBrandsBrandSlugRouteImport.update({
  id: '/$brandSlug',
  path: '/$brandSlug',
  getParentRoute: () => OurBrandsRoute,
} as any)
const InsightsArticleIdRoute = InsightsArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/our-brands': typeof OurBrandsRouteWithChildren
  '/private-label': typeof PrivateLabelRoute
  '/insights/$articleId': typeof InsightsArticleIdRoute
  '/our-brands/$brandSlug': typeof OurBrandsBrandSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/our-brands': typeof OurBrandsRouteWithChildren
  '/private-label': typeof PrivateLabelRoute
  '/insights/$articleId': typeof InsightsArticleIdRoute
  '/our-brands/$brandSlug': typeof OurBrandsBrandSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/our-brands': typeof OurBrandsRouteWithChildren
  '/private-label': typeof PrivateLabelRoute
  '/insights/$articleId': typeof InsightsArticleIdRoute
  '/our-brands/$brandSlug': typeof OurBrandsBrandSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/insights'
    | '/our-brands'
    | '/private-label'
    | '/insights/$articleId'
    | '/our-brands/$brandSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/insights'
    | '/our-brands'
    | '/private-label'
    | '/insights/$articleId'
    | '/our-brands/$brandSlug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/insights'
    | '/our-brands'
    | '/private-label'
    | '/insights/$articleId'
    | '/our-brands/$brandSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  OurBrandsRoute: typeof OurBrandsRouteWithChildren
  PrivateLabelRoute: typeof PrivateLabelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/private-label': {
      id: '/private-label'
      path: '/private-label'
      fullPath: '/private-label'
      preLoaderRoute: typeof PrivateLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-brands': {
      id: '/our-brands'
      path: '/our-brands'
      fullPath: '/our-brands'
      preLoaderRoute: typeof OurBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-brands/$brandSlug': {
      id: '/our-brands/$brandSlug'
      path: '/$brandSlug'
      fullPath: '/our-brands/$brandSlug'
      preLoaderRoute: typeof OurBrandsBrandSlugRouteImport
      parentRoute: typeof OurBrandsRoute
    }
    '/insights/$articleId': {
      id: '/insights/$articleId'
      path: '/$articleId'
      fullPath: '/insights/$articleId'
      preLoaderRoute: typeof InsightsArticleIdRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsArticleIdRoute: typeof InsightsArticleIdRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsArticleIdRoute: InsightsArticleIdRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface OurBrandsRouteChildren {
  OurBrandsBrandSlugRoute: typeof OurBrandsBrandSlugRoute
}

const OurBrandsRouteChildren: OurBrandsRouteChildren = {
  OurBrandsBrandSlugRoute: OurBrandsBrandSlugRoute,
}

const OurBrandsRouteWithChildren = OurBrandsRoute._addFileChildren(
  OurBrandsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRouteWithChildren,
  OurBrandsRoute: OurBrandsRouteWithChildren,
  PrivateLabelRoute: PrivateLabelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
